export const API = 'http://10.105.43.136:8080/';
export const FETCH_UPDATE_DETAILS = 'FETCH_UPDATE_DETAILS';
export const FETCH_UPDATE_DETAIL = 'FETCH_UPDATE_DETAIL';
export const ADD_UPDATE_DETAIL = 'ADD_UPDATE_DETAIL';
export const ADD_UPDATE_DETAILS = 'ADD_UPDATE_DETAILS';
export const ADD_BATCH_UPDATE = 'ADD_BATCH_UPDATE';
export const ADD_BATCH_UPDATES = 'ADD_BATCH_UPDATES';
export const FETCH_STORE = 'FETCH_STORE';
export const FETCH_STORES = 'FETCH_STORES';
export const ADD_STORE = 'ADD_STORE';
export const ADD_STORES = 'ADD_STORES';
export const FETCH_STORE_ERROR = 'FETCH_STORE_ERROR';
export const FETCH_STORE_ERRORS = 'FETCH_STORE_ERRORS';
export const ADD_STORE_ERROR = 'ADD_STORE_ERROR';
export const ADD_STORE_ERRORS = 'ADD_STORE_ERRORS';


